import PWAInstall from '@khmyznikov/pwa-install/react-legacy';
import {tabContainer} from '@xh/hoist/cmp/tab';
import {elementFactory, hoistCmp, uses} from '@xh/hoist/core';
import {panel} from '@xh/hoist/mobile/cmp/panel';
import {AppModel} from './AppModel';
import './App.scss';
import '../core/styles/Musiclub.scss';

export const AppComponent = hoistCmp({
    displayName: 'App',
    model: uses(AppModel),

    render({model}) {
        return panel({
            items: [
                tabContainer(),
                pwaInstall({
                    // Generated by hoist-dev-utils as per webpack.config.js.
                    manifestUrl: '/public/mobile/manifest.json',
                    // Captured at top of AppModel.ts.
                    externalPromptEvent: window['pwaInstallEvent'],
                    // We add a dedicated button to the Settings page that a user can tap to trigger,
                    // without popping up anything automatically b/c that drives ATM completely crazy.
                    manualApple: true,
                    manualChrome: true,
                    ref: model.pwaInstallRef,
                    installDescription: model.pwaInstallDescription
                })
            ],
            mask: 'onLoad'
        });
    }
});

const pwaInstall = elementFactory(PWAInstall);
